Bonjour à tous.tes,<br>
Organizational Theory est un projet que nous devons réaliser dans le cadre de notre<br>
formation Pré-MSC à EPITECH. Ce projet consiste à collecter plusieurs informations en lien avec<br>
les entreprises où nous réalisons notre alternance.<br>
Ces données concernent principalement les circuits d’organisation de nos équipes, les moyens de<br>
communication ainsi que la comparaison entre elles. Pour ce faire, nous avons réalisé ce<br>
questionnaire de ** questions.<br>
Merci beaucoup par avance du temps que vous nous accorderez. Nous restons bien<br>
évidemment à votre écoute pour toute remarque ou question, n’hésitez pas à nous solliciter ! 